name: Generate PDF and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker://docker:19.03.13

    - name: Generate PDF
      run: |
        docker build -t peterpaul/songbook . && docker run -v $(pwd)/src:/songbook/src -v $(pwd)/out:/songbook/out  peterpaul/songbook

    - name: Deploy PDF to Artifactory
      id: deploy_pdf
      uses: actions/upload-artifact@v2
      with:
        name: pdf-file
        path: out/main.pdf
        
    - name: Update GitHub Profile README
      uses: theboi/github-update-readme@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        subhead: "[Download the PDF](${{ steps.deploy_pdf.outputs.url }}/pdf-file)"
        
